name: CI Build (Android 13 / a13_eol)

on:
  push:
    branches: [a13]
  workflow_dispatch:

jobs:
  build_app:
    runs-on: macos-latest
    name: Build App
    steps:
      - name: Checkout Git Repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Setup JDK
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6
        with:
          validate-wrappers: false
          cache-overwrite-existing: true

      - name: Build with Gradle (Debug)
        shell: bash
        run: |
          ./gradlew assembleDebug --stacktrace

      - name: Find APKs
        run: |
          APK_FILE=$(find app/build/outputs/apk/debug -name '*.apk' | head -1)
          echo "APK_FILE=$APK_FILE" >> $GITHUB_ENV
          echo "APK_FILE_NAME=$(basename $APK_FILE .apk)" >> $GITHUB_ENV

      - name: Show APKs SHA256
        if: success()
        run: |
          echo "### Build Success" >> $GITHUB_STEP_SUMMARY
          echo "|Artifact|SHA256|" >> $GITHUB_STEP_SUMMARY
          echo "|:---:|:---|" >> $GITHUB_STEP_SUMMARY
          APK_SHA256=($(shasum -a 256 ${{ env.APK_FILE }}))
          echo "|Debug|$APK_SHA256" >> $GITHUB_STEP_SUMMARY

      - name: Upload APKs
        uses: actions/upload-artifact@v7
        with:
          name: ${{ env.APK_FILE_NAME }}
          path: ${{ env.APK_FILE }}
          compression-level: 9
